---
title: "Economic Time Series"
output: html_document
---

This code reproduces the example from `ggplot2` book. We are going to use two data sets from `ggplot2` library. First data has information on US presidential tenures. The second data set has macroeconomic time series.

```{r echo=TRUE}
library(ggplot2)
head(presidential)
head(economics)
```


```{r echo=TRUE}

# Retain only the 
pres2 <- subset(presidential, start > economics$date[1])

ggplot(economics) + 
  geom_rect(aes(xmin = start, 
                xmax = end, 
                fill = party), 
            data = pres2,
            ymin = -Inf, 
            ymax = Inf, 
            alpha = 1) +
  scale_fill_manual(values = c("blue", "red")) +
  geom_vline(aes(xintercept = as.numeric(start)), 
             data = pres2, 
             colour = "white", 
             alpha = 0.5) + 
  geom_text(aes(x = start + (end - start)/2, 
                y = 2500, 
                label = name, 
                family = "Impact"), 
            data = pres2,
            size = 4, 
            vjust = 0.5, 
            hjust = 0, 
            nudge_x = 50, 
            angle = 90, 
            color = "white") + 
  geom_line(aes(date, unemploy), 
            color = "white", 
            size = 1) + 
  labs(x = "Year", 
       y = "Unemployment '000", 
       fill = "Party") +
  scale_x_date(breaks = pres2$start, 
               labels = scales::date_format("%m-%Y")) +
  theme(panel.grid = element_blank(),
        panel.background = element_blank(),
        axis.line = element_line(color = "black"),
        axis.text.x = element_text(angle = 30, 
                                   hjust = 1))
```

```{r echo=TRUE}

# Retain only the 
pres2 <- subset(presidential, start > economics$date[1])

ggplot(economics) + 
  geom_rect(aes(xmin = start, 
                xmax = end, 
                fill = party), 
            data = pres2,
            ymin = -Inf, 
            ymax = Inf, 
            alpha = 1) +
  scale_fill_manual(values = c("blue", "red")) +
  geom_vline(aes(xintercept = as.numeric(start)), 
             data = pres2, 
             colour = "white", 
             alpha = 0.5) + 
  geom_text(aes(x = start + (end - start)/2, 
                y = 25, 
                label = name, 
                family = "Gabriola"), 
            data = pres2,
            size = 4, 
            vjust = 0.5, 
            hjust = 0, 
            nudge_x = 50, 
            angle = 90, 
            color = "white") + 
  geom_line(aes(date, uempmed), 
            color = "white", 
            size = 1) + 
  scale_y_continuous(limits = c(0,30)) +
  labs(x = "Year", 
       y = "Unemployment %", 
       fill = "Party") +
  scale_x_date(breaks = pres2$start) +
  theme(panel.grid = element_blank(),
        panel.background = element_blank(),
        axis.line = element_line(color = "black"),
        axis.text.x = element_text(angle = 30, hjust = 1))
```


```{r}
ggsave("unemployment.png", height = 7, width = 10)
```

